/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HowWeWorkRouteImport } from './routes/how-we-work'
import { Route as HowWeWorkSplatRouteImport } from './routes/how-we-work.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeWorkRoute = HowWeWorkRouteImport.update({
  id: '/how-we-work',
  path: '/how-we-work',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeWorkSplatRoute = HowWeWorkSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => HowWeWorkRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/how-we-work': typeof HowWeWorkRouteWithChildren
  '/how-we-work/$': typeof HowWeWorkSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/how-we-work': typeof HowWeWorkRouteWithChildren
  '/how-we-work/$': typeof HowWeWorkSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/how-we-work': typeof HowWeWorkRouteWithChildren
  '/how-we-work/$': typeof HowWeWorkSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/how-we-work' | '/how-we-work/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/how-we-work' | '/how-we-work/$'
  id: '__root__' | '/' | '/how-we-work' | '/how-we-work/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HowWeWorkRoute: typeof HowWeWorkRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-work': {
      id: '/how-we-work'
      path: '/how-we-work'
      fullPath: '/how-we-work'
      preLoaderRoute: typeof HowWeWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-work/$': {
      id: '/how-we-work/$'
      path: '/$'
      fullPath: '/how-we-work/$'
      preLoaderRoute: typeof HowWeWorkSplatRouteImport
      parentRoute: typeof HowWeWorkRoute
    }
  }
}

interface HowWeWorkRouteChildren {
  HowWeWorkSplatRoute: typeof HowWeWorkSplatRoute
}

const HowWeWorkRouteChildren: HowWeWorkRouteChildren = {
  HowWeWorkSplatRoute: HowWeWorkSplatRoute,
}

const HowWeWorkRouteWithChildren = HowWeWorkRoute._addFileChildren(
  HowWeWorkRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HowWeWorkRoute: HowWeWorkRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
